export enum ENVEnum {
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  FRONTEND_URL = 'FRONTEND_URL',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  // GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  // STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  // STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',
}
